### PR TITLE
Update gem dependencies to get install with Vagrant v1.9.3 to work

### LINKED ISSUE #140: Fails to install on Vagrant v1.9.3
# Summary
When trying to install this plugin on Vagrant 1.9.3, it fails.

# Environment Info
- OS:  Ubuntu 16.04
- Vagrant:  1.9.3 installed via deb file

# Error message
```
$ vagrant plugin install vagrant-vcloud
Installing the 'vagrant-vcloud' plugin. This can take a few minutes...                                                                                                                 
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate httpclient-2.3.4.1, already activated httpclient-2.8.3 (Gem::LoadError)
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'                                                                                         
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:357:in `block in activate_solution'                                                                  
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:354:in `each'                                                                                        
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:354:in `activate_solution'                                                                           
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:279:in `internal_install'                                                                            
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:104:in `install'                                                                                     
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'                                                               
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/manager.rb:72:in `call'                                                                                  
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/manager.rb:72:in `install_plugin'                                                                        
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/action/install_gem.rb:29:in `call'                                                                  
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'                                                                                   
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builder.rb:116:in `call'                                                                                 
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `block in run'                                                                           
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/busy.rb:19:in `busy'                                                                                       
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `run'                                                                                    
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/base.rb:14:in `action'                                                                      
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/install.rb:32:in `block in execute'                                                         
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/install.rb:31:in `each'                                                                     
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/install.rb:31:in `execute'                                                                  
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/root.rb:66:in `execute'                                                                     
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/cli.rb:42:in `execute'                                                                                          
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:308:in `cli'                                                                                     
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/bin/vagrant:127:in `<main>'                                                                                                 
```

# Possible Solutions
- Update the httpclient gem requirement
- Others?

### PR DESCRIPTION
**Pull request by dandunckelman**
Resolves #140

**NOTE:** I'm still working on testing if the plugin actually works with Vagrant v1.9.3.  This is just to solve the first hurdle of installation.

### CODE REVIEW

**Comment by dandunckelman** [comment]
**UPDATE**
- I built the gem
- Successfully installed from the gem
- Ran Vagrant to build a multi-machine vApp and hit this error:

```
288.398 ERR /var/people/appuser/.vagrant.d/gems/2.2.5/gems/vagrant-vcloud-0.4.6/lib/vagrant-vcloud/driver/version_5_1.rb:1007:in `recompose_vapp_from_vm': undefined method `[]' for nil:NilClass (NoMethodError)
```

That points to [this line of code](https://github.com/dandunckelman/vagrant-vcloud/blob/fix_install_for_vagrant_193/lib/vagrant-vcloud/driver/version_5_1.rb#L1007)

I'm going to rebuild the gem incorporating the change from https://github.com/frapposelli/vagrant-vcloud/pull/137/files

**Comment by dandunckelman** [comment]
This may duplicate #137

**Comment by dandunckelman** [comment]
After rebuilding the gem w/ the change in https://github.com/frapposelli/vagrant-vcloud/pull/137, things worked as expected.

I'm closing this in favor of that PR
